### ISSUE TITLE
Sass problems

### ISSUE THREAD

**Issue by RobinKnipe** [UKHomeOffice/hof-example-form#102]
I think we should add a note about potential installation problems caused by Sass. The fix is simple enough - `rm -fr node_modules ; npm install` - but I've seen a couple of people run into problems here. Perhaps more could be done to check the users' environment before installation?

**Comment by joefitter** [comment]
[https://xkcd.com/1171/]({replace Perl with Sass})

**Comment by joefitter** [comment]
this is only an issue with NPM<3, upgrade and all is well.

**Comment by RobinKnipe** [comment]
Indeed, but for someone who doesn't know their `npm` version, tries to install, fails, upgrades, and tries to install again they will just keep getting errors, and not terribly helpful errors either... just ask @jcavell !

**Comment by easternbloc** [comment]
So, there is documentation that explains the need for npm>3 here:

https://github.com/UKHomeOffice/hof-example-form/blob/master/README.md#prerequisities

And I've just raised a pr to tell NPM to WARN on if you use the wrong versions.

https://github.com/UKHomeOffice/hof-example-form/pull/104

Sadly there's a bug in NPM (https://github.com/npm/npm/issues/5218) which means you won't get much help from NPM regarding this right now but reading the docs will help you.
