### ISSUE TITLE
Ew SCRIPTS

### ISSUE THREAD

**Issue by RobinKnipe** [UKHomeOffice/hof-example-form#103]
I think there's too much being done in the `scripts` section of `package.json`. Issues with the scripts are can be tricky to diagnose because of the way `npm` reports errors, which doesn't help. Also the `npm` error reporting is not pretty - it's often hard to see what a problem is and where it's coming from.
I would recommend refactoring the bulk of the `scripts` section into `grunt` or `gulp` or something similar.

**Comment by joefitter** [comment]
![](https://media3.giphy.com/media/4lsKITftHaUpi/200.gif)

**Comment by joefitter** [comment]
psht, such an NPM hater

**Comment by RobinKnipe** [comment]
No not really - I think the `scripts` section is a great way of handling lots of common dev tasks, and am not suggesting everything should be refactored - but when you have to start writing lots of bash in there, and running `npm` from `npm`, the whole thing gets complex and messy.
Given that HOF is an attempt to build forms from generic configuration and template reuse rather than recoding the same thing again and again, I'd have thought that a task-runner would be something in-keeping with the spirit of the project.

**Comment by joefitter** [comment]
TBH I have no problem with taskrunners and you make a good point that the gulp config could be included as part of the library. IMO the main benefit would be not to have to copy a load of scripts over into each proj, and if error handling/reporting is better then I'm all for it.  @JoeChapman @easternbloc @daniel-ac-martin @danielepolencic ?

**Comment by easternbloc** [comment]
For the example form we want to stay as light as possible. NPM is needed to install the app so we use that as a way of orchestrating our example. Task runners are more layers that are not needed to convey how an "example form" may be put together.
