### ISSUE TITLE
Iteratively update the example form with every new feature

### ISSUE THREAD

**Issue by sulthan-ahmed** [UKHomeOffice/hof-example-form#13]
As part of my Hof Spike/feasibility, our RT/EVW/GE teams agreed it would be helpful if the example up was constantly updated whenever a new feature was added. I've noticed it hasn't been updated since I last used it from November e.g.
1. The BRP app has a feature for typeheads. My team was interested in incorporating so it would be useful to see
2. Having a title on each page
etc

**Comment by easternbloc** [comment]
Hi @sulthan-ahmed I agree this is something we should be doing. I think the most likely way this will be achieved is to create an issue for things that are outstanding. Would it be possible for you to raise an issue for the typeahead and anything else you can think of right now?

In the future we will add hof-example-form to the estimation of new features so we can ensure it's kept up to date.

I'll leave this ticket open for any other syncing that needs doing to date.

**Comment by easternbloc** [comment]
I think this is now complete

**Comment by sulthan-ahmed** [comment]
:+1:  Isn't this never ending? :-D

**Comment by easternbloc** [comment]
lol yes but don't think you're having a ticket open forever haha

**Comment by sulthan-ahmed** [comment]
hahaa fair enough.  I'll contribute where I can
